- name: create node_exporter download dir
  file:
    path: /root/node_exporter
    state: directory
    mode: '0755'

- name: download latest node_exporter
  shell: |
    set -o pipefail
    curl {{ node_exporter_binary_url | quote }} | grep "browser_download_url" | grep -Eo 'https://[^\"]*' | grep linux-amd64 | xargs wget -O /root/node_exporter/archive.tar.gz
    chmod 0700 /root/node_exporter/archive.tar.gz
  args:
    executable: /bin/bash  

- name: unarchive node_exporter
  unarchive:
    src: /root/node_exporter/archive.tar.gz
    remote_src: yes
    dest: /root/node_exporter

- name: copy node_exporter binary
  shell: |
    set -o pipefail
    cp /root/node_exporter/node_exporter*linux-amd64/node_exporter /usr/local/bin/
    chmod 755 /usr/local/bin/node_exporter
    chown root:root /usr/local/bin/node_exporter
  args:
    executable: /bin/bash
  changed_when: False

- name: create node_exporter systemd unit
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '600'

- name: start node_exporter service
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
