---
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce
  apt: name=docker-ce state=latest

- name: Install docker-compose
  apt: name=docker-compose state=latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Install Docker Driver Plugin
  shell: |
    if ! docker plugin ls | grep loki ; then
      docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
    fi