---
# tasks file for polkadot-validator
- name: apt
  import_tasks: apt.yml

- name: journald config
  import_tasks: journald.yml

- name: docker setup
  import_tasks: docker.yml

- name: motd
  import_tasks: motd.yml

- name: proxy setup
  import_role: 
    name: nginx-auth

- name: user
  import_tasks: user.yml  

- name: node exporter
  import_role:
    name: node-exporter  

- name: firewall
  import_tasks: firewall.yml      

# - name: vpn
#   import_tasks: vpn.yml  