---
- name: Install required packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'openresolv', 'wireguard' ]

- name: copy config
  copy:
    src: '{{ role_path }}/files/vpn/{{ vpn }}.conf'
    dest: /etc/wireguard/{{ vpn }}.conf

- name: start service
  systemd:
    name: wg-quick@{{ vpn }}
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false

# - name: stop service
#   systemd:
#     name: wg-quick@{{ vpn }}
#     state: stopped
#     enabled: no
#   changed_when: false      

