---

#curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "author_rotateKeys", "params":[]}' http://localhost:9944 
- name: rotate server keys
  uri:
    url: http://{{ ws_listen }}
    method: "POST"
    body_format: json
    body: |
      { "jsonrpc":"2.0", "method":"author_rotateKeys", "params":[], "id":1 }
  register: rotate_keys

- name: show rotateKeys output
  debug:
    var: rotate_keys

- name: save rotateKeys output
  copy:
    content: "{{ rotate_keys.json }}"
    dest: '{{data_path}}/{{chain}}_rotate_keys.log'


#a check can be made by triggering:
#curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "author_hasSessionKeys", "params":["key"]}' http://localhost:9944  