- name: Ensure Nginx directory exists
  file:
    path: /etc/nginx
    state: directory

- name: create nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: create nginx default site folder, empty, we don't want a default website
  file:
    path: /etc/nginx/sites-enabled/default
    state: directory    

- name: check if .htpasswd file already exists
  stat:
    path: /etc/nginx/.htpasswd
  register: htpasswd_file

- name: remove libapr related packages
  apt:
    pkg:
    - libapr1
    - libaprutil1
    state: absent
    update_cache: yes
    autoremove: yes
  when: not htpasswd_file.stat.exists

- name: install apache2-utils
  apt:
    name: apache2-utils
    state: present
    update_cache: yes
  when: not htpasswd_file.stat.exists

- name: generate .htpasswd file
  shell: |
    set -o pipefail
    htpasswd -bc /etc/nginx/.htpasswd {{ nginx_user }} {{ nginx_password }}
    chmod 600 /etc/nginx/.htpasswd
    chown www-data:www-data /etc/nginx/.htpasswd
  args:
    executable: /bin/bash
  changed_when: true
  tags: molecule-idempotence-notest

- name: create nginx config for node exporter
  copy:
    src: node_exporter.nginx.conf
    dest: /etc/nginx/sites-enabled/node-exporter.conf

- name: create nginx config for polkadot metrics
  copy:
    src: polkadot_metrics.nginx.conf
    dest: /etc/nginx/sites-enabled/polkadot-metrics.conf
